package online.militarygame.mongodatabase.initiaion;

import online.militarygame.mongodatabase.enums.unit.MovementType;
import online.militarygame.mongodatabase.models.TileType;

import java.util.HashMap;
import java.util.Map;

public class TileInitiation {
	public static final int GRASS = 100;
	public static final int ROAD = 200;
	public static final int FOREST = 300;
	public static final int MOUNTAIN = 400;
	public static final int RIVER = 500;

	public static final int SHALLOW_WATER = 1000;
	public static final int DEEP_WATER = 1200;
	public static final int STRONG_CURRENT_WATER = 1300;
	public static final int ROCK_WATER = 4300;

	public static final int BARRIER = 2000;
	public static final int BROKEN_BARRIER = 2100;
	public static final int BREAKABLE_BARRIER = 2200;

	public static final int AIR = 3000;

	public static final int TOWN = 4000;
	public static final int BARRACKS = 4100;
	public static final int DOCK = 4200;
	public static final int AIRPORT = 4300;
	public static final int PRESIDENT_OFFICE = 4400;
	public static final int UNIVERSITY = 4500;
	public static final int TEMPLE = 4600;

	public static Map<Integer, TileType> makeTileTypeMap1()
	{
		Map<Integer, TileType> tileTypeMap = new HashMap<>();

		TileType grass = new TileType();
		grass.setId(GRASS);
		grass.setName("General");
		grass.setDescription("Does literally nothing");
		grass.setGraphicsPath("/TileTypes/general.svg");
		grass.setDefenseRating(1);
		Map<MovementType, Integer> grassMovementCosts = new HashMap<>();
		grassMovementCosts.put(MovementType.FOOT, 1);
		grassMovementCosts.put(MovementType.FOOT2, 2);
		grassMovementCosts.put(MovementType.TIRE, 2);
		grassMovementCosts.put(MovementType.TRACK, 1);
		grassMovementCosts.put(MovementType.DEEP_WATER, null);
		grassMovementCosts.put(MovementType.ALL_WATER, null);
		grassMovementCosts.put(MovementType.FLYING, 1);
		grassMovementCosts.put(MovementType.BARRIER, null);
		grassMovementCosts.put(MovementType.FREE_GROUND, 1);
		grassMovementCosts.put(MovementType.FREE_WATER, null);
		grassMovementCosts.put(MovementType.FREE, 1);
		grass.setMovementTypeCosts(grassMovementCosts);
		putToMap(grass, tileTypeMap);

		TileType road = new TileType();
		road.setId(ROAD);
		road.setName("Road");
		road.setDescription("Road");
		road.setGraphicsPath("/TileTypes/road.svg");
		road.setDefenseRating(0);
		Map<MovementType, Integer> roadMovementCosts = new HashMap<>();
		roadMovementCosts.put(MovementType.FOOT, 1);
		roadMovementCosts.put(MovementType.FOOT2, 1);
		roadMovementCosts.put(MovementType.TIRE, 1);
		roadMovementCosts.put(MovementType.TRACK, 1);
		roadMovementCosts.put(MovementType.DEEP_WATER, null);
		roadMovementCosts.put(MovementType.ALL_WATER, null);
		roadMovementCosts.put(MovementType.FLYING, 1);
		roadMovementCosts.put(MovementType.BARRIER, null);
		roadMovementCosts.put(MovementType.FREE_GROUND, 1);
		roadMovementCosts.put(MovementType.FREE_WATER, null);
		roadMovementCosts.put(MovementType.FREE, 1);
		road.setMovementTypeCosts(roadMovementCosts);
		putToMap(road, tileTypeMap);
		
		TileType forest = new TileType();
		forest.setId(FOREST);
		forest.setName("Forest");
		forest.setDescription("Forest");
		forest.setGraphicsPath("/TileTypes/forest.svg");
		forest.setDefenseRating(2);
		Map<MovementType, Integer> forestMovementCosts = new HashMap<>();
		forestMovementCosts.put(MovementType.FOOT, 1);
		forestMovementCosts.put(MovementType.FOOT2, 1);
		forestMovementCosts.put(MovementType.TIRE, 3);
		forestMovementCosts.put(MovementType.TRACK, 2);
		forestMovementCosts.put(MovementType.DEEP_WATER, 0);
		forestMovementCosts.put(MovementType.ALL_WATER, 0);
		forestMovementCosts.put(MovementType.FLYING, 1);
		forestMovementCosts.put(MovementType.BARRIER, 0);
		forestMovementCosts.put(MovementType.FREE_GROUND, 1);
		forestMovementCosts.put(MovementType.FREE_WATER, 2);
		forestMovementCosts.put(MovementType.FREE, 1);
		forest.setMovementTypeCosts(forestMovementCosts);
		putToMap(forest, tileTypeMap);
		
		TileType mountain = new TileType();
		mountain.setId(MOUNTAIN);
		mountain.setName("Mountain");
		mountain.setDescription("Mountain");
		mountain.setGraphicsPath("/TileTypes/mountain.svg");
		mountain.setDefenseRating(4);
		Map<MovementType, Integer> mountainMovementCosts = new HashMap<>();
		mountainMovementCosts.put(MovementType.FOOT, 2);
		mountainMovementCosts.put(MovementType.FOOT2, 1);
		mountainMovementCosts.put(MovementType.TIRE, null);
		mountainMovementCosts.put(MovementType.TRACK, null);
		mountainMovementCosts.put(MovementType.DEEP_WATER, null);
		mountainMovementCosts.put(MovementType.ALL_WATER, null);
		mountainMovementCosts.put(MovementType.FLYING, 1);
		mountainMovementCosts.put(MovementType.BARRIER, null);
		mountainMovementCosts.put(MovementType.FREE_GROUND, 1);
		mountainMovementCosts.put(MovementType.FREE_WATER, null);
		mountainMovementCosts.put(MovementType.FREE, 1);
		mountain.setMovementTypeCosts(mountainMovementCosts);
		putToMap(mountain, tileTypeMap);
		
		TileType river = new TileType();
		river.setId(RIVER);
		river.setName("River");
		river.setDescription("River");
		river.setGraphicsPath("/TileTypes/river.svg");
		river.setDefenseRating(0);
		Map<MovementType, Integer> riverMovementCosts = new HashMap<>();
		riverMovementCosts.put(MovementType.FOOT, 1);
		riverMovementCosts.put(MovementType.FOOT2, 2);
		riverMovementCosts.put(MovementType.TIRE, null);
		riverMovementCosts.put(MovementType.TRACK, null);
		riverMovementCosts.put(MovementType.DEEP_WATER, null);
		riverMovementCosts.put(MovementType.ALL_WATER, null);
		riverMovementCosts.put(MovementType.FLYING, 1);
		riverMovementCosts.put(MovementType.BARRIER, null);
		riverMovementCosts.put(MovementType.FREE_GROUND, 1);
		riverMovementCosts.put(MovementType.FREE_WATER, null);
		riverMovementCosts.put(MovementType.FREE, 1);
		river.setMovementTypeCosts(riverMovementCosts);
		putToMap(river, tileTypeMap);
		
		TileType shallow_water = new TileType();
		shallow_water.setId(SHALLOW_WATER);
		shallow_water.setName("Shallow_water");
		shallow_water.setDescription("Shallow_water");
		shallow_water.setGraphicsPath("/TileTypes/shallow_water.svg");
		shallow_water.setDefenseRating(0);
		Map<MovementType, Integer> shallow_waterMovementCosts = new HashMap<>();
		shallow_waterMovementCosts.put(MovementType.FOOT, 1);
		shallow_waterMovementCosts.put(MovementType.FOOT2, 1);
		shallow_waterMovementCosts.put(MovementType.TIRE, 1);
		shallow_waterMovementCosts.put(MovementType.TRACK, 1);
		shallow_waterMovementCosts.put(MovementType.DEEP_WATER, null);
		shallow_waterMovementCosts.put(MovementType.ALL_WATER, 1);
		shallow_waterMovementCosts.put(MovementType.FLYING, 1);
		shallow_waterMovementCosts.put(MovementType.BARRIER, null);
		shallow_waterMovementCosts.put(MovementType.FREE_GROUND, null);
		shallow_waterMovementCosts.put(MovementType.FREE_WATER, 1);
		shallow_waterMovementCosts.put(MovementType.FREE, 1);
		shallow_water.setMovementTypeCosts(shallow_waterMovementCosts);
		putToMap(shallow_water, tileTypeMap);

		TileType deep_water = new TileType();
		deep_water.setId(DEEP_WATER);
		deep_water.setName("Deep_water");
		deep_water.setDescription("Deep_water");
		deep_water.setGraphicsPath("/TileTypes/deep_water.svg");
		deep_water.setDefenseRating(0);
		Map<MovementType, Integer> deep_waterMovementCosts = new HashMap<>();
		deep_waterMovementCosts.put(MovementType.FOOT, null);
		deep_waterMovementCosts.put(MovementType.FOOT2, null);
		deep_waterMovementCosts.put(MovementType.TIRE, null);
		deep_waterMovementCosts.put(MovementType.TRACK, null);
		deep_waterMovementCosts.put(MovementType.DEEP_WATER, null);
		deep_waterMovementCosts.put(MovementType.ALL_WATER, 1);
		deep_waterMovementCosts.put(MovementType.FLYING, 1);
		deep_waterMovementCosts.put(MovementType.BARRIER, null);
		deep_waterMovementCosts.put(MovementType.FREE_GROUND, null);
		deep_waterMovementCosts.put(MovementType.FREE_WATER, 1);
		deep_waterMovementCosts.put(MovementType.FREE, 1);
		deep_water.setMovementTypeCosts(deep_waterMovementCosts);
		putToMap(deep_water, tileTypeMap);

		TileType strongCurrentWater = new TileType();
		strongCurrentWater.setId(STRONG_CURRENT_WATER);
		strongCurrentWater.setName("Strong current water");
		strongCurrentWater.setDescription("Strong current water");
		strongCurrentWater.setGraphicsPath("/TileTypes/strong_current_water.svg");
		strongCurrentWater.setDefenseRating(0);
		Map<MovementType, Integer> strongCurrentMovementCosts = new HashMap<>();
		strongCurrentMovementCosts.put(MovementType.FOOT, null);
		strongCurrentMovementCosts.put(MovementType.FOOT2, null);
		strongCurrentMovementCosts.put(MovementType.TIRE, null);
		strongCurrentMovementCosts.put(MovementType.TRACK, null);
		strongCurrentMovementCosts.put(MovementType.DEEP_WATER, 2);
		strongCurrentMovementCosts.put(MovementType.ALL_WATER, 2);
		strongCurrentMovementCosts.put(MovementType.FLYING, 1);
		strongCurrentMovementCosts.put(MovementType.BARRIER, null);
		strongCurrentMovementCosts.put(MovementType.FREE_GROUND, null);
		strongCurrentMovementCosts.put(MovementType.FREE_WATER, 1);
		strongCurrentMovementCosts.put(MovementType.FREE, 1);
		strongCurrentWater.setMovementTypeCosts(strongCurrentMovementCosts);
		putToMap(strongCurrentWater, tileTypeMap);

		TileType rockWater = new TileType();
		rockWater.setId(ROCK_WATER);
		rockWater.setName("Rock water");
		rockWater.setDescription("Rock water");
		rockWater.setGraphicsPath("/TileTypes/rock_water.svg");
		rockWater.setDefenseRating(1);
		Map<MovementType, Integer> rockWaterMovementCosts = new HashMap<>();
		rockWaterMovementCosts.put(MovementType.FOOT, null);
		rockWaterMovementCosts.put(MovementType.FOOT2, null);
		rockWaterMovementCosts.put(MovementType.TIRE, null);
		rockWaterMovementCosts.put(MovementType.TRACK, null);
		rockWaterMovementCosts.put(MovementType.DEEP_WATER, 2);
		rockWaterMovementCosts.put(MovementType.ALL_WATER, 2);
		rockWaterMovementCosts.put(MovementType.FLYING, 1);
		rockWaterMovementCosts.put(MovementType.BARRIER, null);
		rockWaterMovementCosts.put(MovementType.FREE_GROUND, null);
		rockWaterMovementCosts.put(MovementType.FREE_WATER, 1);
		rockWaterMovementCosts.put(MovementType.FREE, 1);
		rockWater.setMovementTypeCosts(rockWaterMovementCosts);
		putToMap(rockWater, tileTypeMap);
		
		TileType barrier = new TileType();
		barrier.setId(BARRIER);
		barrier.setName("Barrier");
		barrier.setDescription("Barrier");
		barrier.setGraphicsPath("/TileTypes/barrier.svg");
		barrier.setDefenseRating(0);
		Map<MovementType, Integer> barrierMovementCosts = new HashMap<>();
		barrierMovementCosts.put(MovementType.FOOT, null);
		barrierMovementCosts.put(MovementType.FOOT2, null);
		barrierMovementCosts.put(MovementType.TIRE, null);
		barrierMovementCosts.put(MovementType.TRACK, null);
		barrierMovementCosts.put(MovementType.DEEP_WATER, null);
		barrierMovementCosts.put(MovementType.ALL_WATER, null);
		barrierMovementCosts.put(MovementType.FLYING, null);
		barrierMovementCosts.put(MovementType.BARRIER, 1);
		barrierMovementCosts.put(MovementType.FREE_GROUND, 1);
		barrierMovementCosts.put(MovementType.FREE_WATER, null);
		barrierMovementCosts.put(MovementType.FREE, 1);
		barrier.setMovementTypeCosts(barrierMovementCosts);
		putToMap(barrier, tileTypeMap);
		
		TileType broken_barrier = new TileType();
		broken_barrier.setId(BROKEN_BARRIER);
		broken_barrier.setName("Broken_barrier");
		broken_barrier.setDescription("Broken_barrier");
		broken_barrier.setGraphicsPath("/TileTypes/broken_barrier.svg");
		broken_barrier.setDefenseRating(1);
		Map<MovementType, Integer> broken_barrierMovementCosts = new HashMap<>();
		broken_barrierMovementCosts.put(MovementType.FOOT, 1);
		broken_barrierMovementCosts.put(MovementType.FOOT2, 1);
		broken_barrierMovementCosts.put(MovementType.TIRE, 2);
		broken_barrierMovementCosts.put(MovementType.TRACK, 1);
		broken_barrierMovementCosts.put(MovementType.DEEP_WATER, null);
		broken_barrierMovementCosts.put(MovementType.ALL_WATER, null);
		broken_barrierMovementCosts.put(MovementType.FLYING, 1);
		broken_barrierMovementCosts.put(MovementType.BARRIER, null);
		broken_barrierMovementCosts.put(MovementType.FREE_GROUND, 1);
		broken_barrierMovementCosts.put(MovementType.FREE_WATER, null);
		broken_barrierMovementCosts.put(MovementType.FREE, 1);
		broken_barrier.setMovementTypeCosts(broken_barrierMovementCosts);
		putToMap(broken_barrier, tileTypeMap);
		
		TileType breakable_barrier = new TileType();
		breakable_barrier.setId(BREAKABLE_BARRIER);
		breakable_barrier.setName("Breakable_barrier");
		breakable_barrier.setDescription("Breakable_barrier");
		breakable_barrier.setGraphicsPath("/TileTypes/breakable_barrier.svg");
		breakable_barrier.setDefenseRating(0);
		Map<MovementType, Integer> breakable_barrierMovementCosts = new HashMap<>();
		breakable_barrierMovementCosts.put(MovementType.FOOT, null);
		breakable_barrierMovementCosts.put(MovementType.FOOT2, null);
		breakable_barrierMovementCosts.put(MovementType.TIRE, null);
		breakable_barrierMovementCosts.put(MovementType.TRACK, null);
		breakable_barrierMovementCosts.put(MovementType.DEEP_WATER, null);
		breakable_barrierMovementCosts.put(MovementType.ALL_WATER, null);
		breakable_barrierMovementCosts.put(MovementType.FLYING, null);
		breakable_barrierMovementCosts.put(MovementType.BARRIER, 1);
		breakable_barrierMovementCosts.put(MovementType.FREE_GROUND, 1);
		breakable_barrierMovementCosts.put(MovementType.FREE_WATER, null);
		breakable_barrierMovementCosts.put(MovementType.FREE, 1);
		breakable_barrier.setMovementTypeCosts(breakable_barrierMovementCosts);
		putToMap(breakable_barrier, tileTypeMap);
		
		TileType air = new TileType();
		air.setId(AIR);
		air.setName("Air");
		air.setDescription("Air");
		air.setGraphicsPath("/TileTypes/air.svg");
		air.setDefenseRating(0);
		Map<MovementType, Integer> airMovementCosts = new HashMap<>();
		airMovementCosts.put(MovementType.FOOT, null);
		airMovementCosts.put(MovementType.FOOT2, null);
		airMovementCosts.put(MovementType.TIRE, null);
		airMovementCosts.put(MovementType.TRACK, null);
		airMovementCosts.put(MovementType.DEEP_WATER, null);
		airMovementCosts.put(MovementType.ALL_WATER, null);
		airMovementCosts.put(MovementType.FLYING, 1);
		airMovementCosts.put(MovementType.BARRIER, null);
		airMovementCosts.put(MovementType.FREE_GROUND, null);
		airMovementCosts.put(MovementType.FREE_WATER, null);
		airMovementCosts.put(MovementType.FREE, 1);
		air.setMovementTypeCosts(airMovementCosts);
		putToMap(air, tileTypeMap);
		
		TileType town = new TileType();
		town.setId(TOWN);
		town.setName("Town");
		town.setDescription("Town");
		town.setGraphicsPath("/TileTypes/town.svg");
		town.setDefenseRating(3);
		Map<MovementType, Integer> townMovementCosts = new HashMap<>();
		townMovementCosts.put(MovementType.FOOT, 1);
		townMovementCosts.put(MovementType.FOOT2, 1);
		townMovementCosts.put(MovementType.TIRE, 1);
		townMovementCosts.put(MovementType.TRACK, 1);
		townMovementCosts.put(MovementType.DEEP_WATER, null);
		townMovementCosts.put(MovementType.ALL_WATER, null);
		townMovementCosts.put(MovementType.FLYING, 1);
		townMovementCosts.put(MovementType.BARRIER, null);
		townMovementCosts.put(MovementType.FREE_GROUND, 1);
		townMovementCosts.put(MovementType.FREE_WATER, null);
		townMovementCosts.put(MovementType.FREE, 1);
		town.setMovementTypeCosts(townMovementCosts);
		putToMap(town, tileTypeMap);
		
		TileType barracks = new TileType();
		barracks.setId(BARRACKS);
		barracks.setName("Barracks");
		barracks.setDescription("Barracks");
		barracks.setGraphicsPath("/TileTypes/barracks.svg");
		barracks.setDefenseRating(3);
		Map<MovementType, Integer> barracksMovementCosts = new HashMap<>();
		barracksMovementCosts.put(MovementType.FOOT, 1);
		barracksMovementCosts.put(MovementType.FOOT2, 1);
		barracksMovementCosts.put(MovementType.TIRE, 1);
		barracksMovementCosts.put(MovementType.TRACK, 1);
		barracksMovementCosts.put(MovementType.DEEP_WATER, null);
		barracksMovementCosts.put(MovementType.ALL_WATER, null);
		barracksMovementCosts.put(MovementType.FLYING, 1);
		barracksMovementCosts.put(MovementType.BARRIER, 1);
		barracksMovementCosts.put(MovementType.FREE_GROUND, 1);
		barracksMovementCosts.put(MovementType.FREE_WATER, null);
		barracksMovementCosts.put(MovementType.FREE, 1);
		barracks.setMovementTypeCosts(barracksMovementCosts);
		putToMap(barracks, tileTypeMap);
		
		TileType dock = new TileType();
		dock.setId(DOCK);
		dock.setName("Dock");
		dock.setDescription("Dock");
		dock.setGraphicsPath("/TileTypes/dock.svg");
		dock.setDefenseRating(3);
		Map<MovementType, Integer> dockMovementCosts = new HashMap<>();
		dockMovementCosts.put(MovementType.FOOT, 1);
		dockMovementCosts.put(MovementType.FOOT2, 1);
		dockMovementCosts.put(MovementType.TIRE, 1);
		dockMovementCosts.put(MovementType.TRACK, 1);
		dockMovementCosts.put(MovementType.DEEP_WATER, 1);
		dockMovementCosts.put(MovementType.ALL_WATER, 1);
		dockMovementCosts.put(MovementType.FLYING, 1);
		dockMovementCosts.put(MovementType.BARRIER, null);
		dockMovementCosts.put(MovementType.FREE_GROUND, 1);
		dockMovementCosts.put(MovementType.FREE_WATER, 1);
		dockMovementCosts.put(MovementType.FREE, 1);
		dock.setMovementTypeCosts(dockMovementCosts);
		putToMap(dock, tileTypeMap);
		
		TileType airport = new TileType();
		airport.setId(AIRPORT);
		airport.setName("Airport");
		airport.setDescription("Airport");
		airport.setGraphicsPath("/TileTypes/airport.svg");
		airport.setDefenseRating(3);
		Map<MovementType, Integer> airportMovementCosts = new HashMap<>();
		airportMovementCosts.put(MovementType.FOOT, 1);
		airportMovementCosts.put(MovementType.FOOT2, 1);
		airportMovementCosts.put(MovementType.TIRE, 1);
		airportMovementCosts.put(MovementType.TRACK, 1);
		airportMovementCosts.put(MovementType.DEEP_WATER, null);
		airportMovementCosts.put(MovementType.ALL_WATER, null);
		airportMovementCosts.put(MovementType.FLYING, 1);
		airportMovementCosts.put(MovementType.BARRIER, null);
		airportMovementCosts.put(MovementType.FREE_GROUND, 1);
		airportMovementCosts.put(MovementType.FREE_WATER, null);
		airportMovementCosts.put(MovementType.FREE, 1);
		airport.setMovementTypeCosts(airportMovementCosts);
		putToMap(airport, tileTypeMap);
		
		TileType president_office = new TileType();
		president_office.setId(PRESIDENT_OFFICE);
		president_office.setName("President_office");
		president_office.setDescription("President_office");
		president_office.setGraphicsPath("/TileTypes/president_office.svg");
		president_office.setDefenseRating(4);
		Map<MovementType, Integer> president_officeMovementCosts = new HashMap<>();
		president_officeMovementCosts.put(MovementType.FOOT, 1);
		president_officeMovementCosts.put(MovementType.FOOT2, 1);
		president_officeMovementCosts.put(MovementType.TIRE, 1);
		president_officeMovementCosts.put(MovementType.TRACK, 1);
		president_officeMovementCosts.put(MovementType.DEEP_WATER, null);
		president_officeMovementCosts.put(MovementType.ALL_WATER, null);
		president_officeMovementCosts.put(MovementType.FLYING, 1);
		president_officeMovementCosts.put(MovementType.BARRIER, null);
		president_officeMovementCosts.put(MovementType.FREE_GROUND, 1);
		president_officeMovementCosts.put(MovementType.FREE_WATER, null);
		president_officeMovementCosts.put(MovementType.FREE, 1);
		president_office.setMovementTypeCosts(president_officeMovementCosts);
		putToMap(president_office, tileTypeMap);
		
		TileType university = new TileType();
		university.setId(UNIVERSITY);
		university.setName("University");
		university.setDescription("University");
		university.setGraphicsPath("/TileTypes/university.svg");
		university.setDefenseRating(3);
		Map<MovementType, Integer> universityMovementCosts = new HashMap<>();
		universityMovementCosts.put(MovementType.FOOT, 1);
		universityMovementCosts.put(MovementType.FOOT2, 1);
		universityMovementCosts.put(MovementType.TIRE, 1);
		universityMovementCosts.put(MovementType.TRACK, 1);
		universityMovementCosts.put(MovementType.DEEP_WATER, null);
		universityMovementCosts.put(MovementType.ALL_WATER, null);
		universityMovementCosts.put(MovementType.FLYING, 1);
		universityMovementCosts.put(MovementType.BARRIER, null);
		universityMovementCosts.put(MovementType.FREE_GROUND, 1);
		universityMovementCosts.put(MovementType.FREE_WATER, null);
		universityMovementCosts.put(MovementType.FREE, 1);
		university.setMovementTypeCosts(universityMovementCosts);
		putToMap(university, tileTypeMap);
		
		TileType temple = new TileType();
		temple.setId(TEMPLE);
		temple.setName("Temple");
		temple.setDescription("Temple");
		temple.setGraphicsPath("/TileTypes/temple.svg");
		temple.setDefenseRating(3);
		Map<MovementType, Integer> templeMovementCosts = new HashMap<>();
		templeMovementCosts.put(MovementType.FOOT, 1);
		templeMovementCosts.put(MovementType.FOOT2, 1);
		templeMovementCosts.put(MovementType.TIRE, 1);
		templeMovementCosts.put(MovementType.TRACK, 1);
		templeMovementCosts.put(MovementType.DEEP_WATER, null);
		templeMovementCosts.put(MovementType.ALL_WATER, null);
		templeMovementCosts.put(MovementType.FLYING, 1);
		templeMovementCosts.put(MovementType.BARRIER, null);
		templeMovementCosts.put(MovementType.FREE_GROUND, 1);
		templeMovementCosts.put(MovementType.FREE_WATER, null);
		templeMovementCosts.put(MovementType.FREE, 1);
		temple.setMovementTypeCosts(templeMovementCosts);
		putToMap(temple, tileTypeMap);
		

		return tileTypeMap;
	}

	private static void putToMap(TileType TileType, Map<Integer, TileType> TileTypeMap) {
		TileTypeMap.put(TileType.getId(), TileType);
	}
}
